using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using ADV1.PL;

namespace ADV1.PL
{
    public partial class ACHAT : Form
    {
        public int id;
        ADVEntities db = new ADVEntities();
        BL.metod metod = new BL.metod();
        achat tb_achat = new achat();
        
        public ACHAT()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ADV1.ADVEntities dbContext = new ADV1.ADVEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.achats.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.achats.Local.ToBindingList();
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            PL.achat_add frm_add = new achat_add();
            frm_add.id = 0;
            frm_add.btn_ajout.Text = "Ajoute";
            frm_add.Show();
        }

        private void ACHAT_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'aDVDataSet2.achat' table. You can move, or remove it, as needed.
            this.achatTableAdapter.Fill(this.aDVDataSet2.achat);

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {

            PL.achat_add frm_add = new achat_add();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
            tb_achat = db.achats.Where(x => x.id == id).FirstOrDefault();
            frm_add.achat_nom.Text = tb_achat.achat_name.ToString();
            frm_add.cat_txt.Text = tb_achat.achat_cat.ToString();
            frm_add.type_txt.Text = tb_achat.achat_type.ToString();
            frm_add.four_txt.Text = tb_achat.achat_four.ToString();
            frm_add.details_txt.Text = tb_achat.achat_det.ToString();
            frm_add.prix_txt.Text = tb_achat.achat_buy.ToString();
            frm_add.vente_txt.Text = tb_achat.achat_sell.ToString();
            frm_add.qt_txt.Text = tb_achat.achat_qt.ToString();
            frm_add.id = id;
            frm_add.btn_ajout.Text = "Modifier";
            frm_add.Show();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            try
            {
                var rs = MessageBox.Show("Processus de suppression", "Voulez-vous supprimer?", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    EBL.toast toast = new EBL.toast();
                    id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                    tb_achat = db.achats.Where(x => x.id == id).FirstOrDefault();
                    db.Entry(tb_achat).State = EntityState.Deleted;
                    db.SaveChanges();
                    updte_data();
                    toast.txt_caption.Text = "Supprimer";
                    toast.ShowDialog();
                }
                else { }
            }
            catch { }
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            db = new ADVEntities();
            gridControl1.DataSource = db.achats.ToList();
        }
        public void updte_data()
        {
            db = new ADVEntities();
            gridControl1.DataSource = db.achats.ToList();
        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            var search = textBox1.Text;
            gridControl1.DataSource = db.achats.Where(x => x.achat_name.Contains(search)).ToList();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
