using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace ADV1.PL
{
    public partial class Utili : Form
    {
        public int id;
        ADVEntities db = new ADVEntities();
        BL.metod metod = new BL.metod();
        utili tb_utili = new utili();
        public Utili()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ADV1.ADVEntities dbContext = new ADV1.ADVEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.utilis.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.utilis.Local.ToBindingList();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            PL.utili_add uti_add = new utili_add();
            uti_add.id = 0;
            uti_add.btn_add.Text = "Ajoute";
            uti_add.Show();
        }

        private void utili_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'aDVDataSet5.utili' table. You can move, or remove it, as needed.
            this.utiliTableAdapter.Fill(this.aDVDataSet5.utili);

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            PL.utili_add frm_add = new utili_add();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
            tb_utili = db.utilis.Where(x => x.id == id).FirstOrDefault();
            frm_add.nome_txt.Text = tb_utili.utili_user.ToString();
            frm_add.motpass_txt.Text = tb_utili.utili_pass.ToString();
            frm_add.statu_txt.Text = tb_utili.utili_state.ToString();
            frm_add.id = id;
            frm_add.btn_add.Text = "Modifier";
            frm_add.Show();
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            try
            {
                var rs = MessageBox.Show("Processus de suppression", "Voulez-vous supprimer?", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    EBL.toast toast = new EBL.toast();
                    id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                    tb_utili = db.utilis.Where(x => x.id == id).FirstOrDefault();
                    db.Entry(tb_utili).State = EntityState.Deleted;
                    db.SaveChanges();
                    updte_data();
                    toast.txt_caption.Text = "Supprimer";
                    toast.ShowDialog();
                }
                else { }
            }
            catch { }
           
        }
        public void updte_data()
        {
            db = new ADVEntities();
            gridControl1.DataSource = db.utilis.ToList();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {           
                db = new ADVEntities();
                gridControl1.DataSource = db.utilis.ToList();            
        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            var search = textBox1.Text;
            gridControl1.DataSource = db.utilis.Where(x => x.utili_user.Contains(search)).ToList();
        }
    }
}
