using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace ADV1.PL
{
    public partial class Ventes : Form
    {
        public int id;
        ADVEntities db = new ADVEntities();
        BL.metod metod = new BL.metod();
        vente tb_vent = new vente();
        achat tb_achat = new achat();
        client tb_client = new client();
        public Ventes()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ADV1.ADVEntities dbContext = new ADV1.ADVEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.ventes.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.ventes.Local.ToBindingList();
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            PL.ventes_add ventes_add = new ventes_add();
            // cat_add.id = 0;
            ventes_add.btn_ajout.Text = "Ajoute";
            ventes_add.Show();
        }

        private void Ventes_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'aDVDataSet4.vente' table. You can move, or remove it, as needed.
            this.venteTableAdapter.Fill(this.aDVDataSet4.vente);

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            try
            {
                var rs = MessageBox.Show("Processus de suppression", "Voulez-vous supprimer?", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    EBL.toast toast = new EBL.toast();
                    id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                    tb_vent = db.ventes.Where(x => x.id == id).FirstOrDefault();
                    db.Entry(tb_vent).State = EntityState.Deleted;
                    db.SaveChanges();
                    updte_data();
                    toast.txt_caption.Text = "Supprimer";
                    toast.ShowDialog();
                }
                else { }
            }
            catch { }
        }
        public void updte_data()
        {
            db = new ADVEntities();
            gridControl1.DataSource = db.ventes.ToList();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            db = new ADVEntities();
            gridControl1.DataSource = db.ventes.ToList();
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            var search = textBox1.Text;
            gridControl1.DataSource = db.ventes.Where(x => x.vent_name.Contains(search)).ToList();
        }
    }

    }

